### PR TITLE
Add 'deploy environment results' support

### PR DESCRIPTION
**Pull request by lholman**
This PR is simply looking to extend PsBamboo to support retrieving results for 'Deploy Environment' deployments by environmentId, ultimately it add the following two functions.

* `Get-BambooDeployProjectEnvironment.ps1`
* `Get-BambooDeployEnvironmentResult.ps1`

There may be a more elegant way to do this but the Bamboo API seems incredibly inconsistent and I found this the most consumable approach for downstream PS scripts.

Version number bumped to `3.0.0.0` as requested and I have updated the CHANGELOG and README, the following is also passing with flying colours.

```
Invoke-Pester -Path ".\Tests"
```

### CODE REVIEW

**Comment by muratiakos** [comment]
Looking forward to it!

**Comment by muratiakos** [comment]
👍 Looks good! I am wondering if we should bump the version on the module for the new features.

**Review by muratiakos — APPROVED** [review]

**Comment by lholman** [comment]
I'll try and finish this up today so we can get the PR closed down. I just need to update the README and documentation

**Comment by muratiakos** [comment]
Sure! Bump the module version and ping me, when you are ready! Thank you again!

**Comment by lholman** [comment]
@muratiakos I think we're ready to go, shout if you need me to clarify anything. I would like to add some more example usages in a subsequent PR.

**Comment by muratiakos** [comment]
👍 Awesome - Thank you very much @lholman !

**Comment by lholman** [comment]
@muratiakos Not a problem. What's the process for getting these last two versions out to the PowerShell Gallery?

**Comment by muratiakos** [comment]
It is out now on the gallery - https://www.powershellgallery.com/packages/PsBamboo/3.0.0.0  - but I am just moving the deployment to code now, so we can maintain it from code too

**Comment by muratiakos** [comment]
@lholman - Here's the related pipeline PR wip: https://github.com/murati-hu/PsBamboo/pull/4

**Pull request merged**
